import { NextResponse } from 'next/server';
export const dynamic = 'force-dynamic';
const LOCATIONS = [
  { name:'Altos Labs',lat:37.3861,lng:-122.0839,topic:'LONGEVITY',signal:'Biotech',url:'https://altoslabs.com',region:'North America'},
  { name:'Calico Life Sciences',lat:37.4419,lng:-122.1430,topic:'LONGEVITY',signal:'Biotech',url:'https://calicolabs.com',region:'North America'},
  { name:'BioAge Labs',lat:37.8716,lng:-122.2727,topic:'LONGEVITY',signal:'Biotech',url:'https://bioagelabs.com',region:'North America'},
  { name:'Retro Biosciences',lat:37.5485,lng:-122.0597,topic:'LONGEVITY',signal:'Biotech',url:'https://retro.bio',region:'North America'},
  { name:'NewLimit',lat:37.7749,lng:-122.4294,topic:'LONGEVITY',signal:'Biotech',url:'https://newlimit.com',region:'North America'},
  { name:'Insilico Medicine',lat:22.3193,lng:114.1694,topic:'LONGEVITY',signal:'Biotech',url:'https://insilico.com',region:'Asia'},
  { name:'Unity Biotechnology',lat:37.7749,lng:-122.4094,topic:'LONGEVITY',signal:'Biotech',url:'https://unitybiotechnology.com',region:'North America'},
  { name:'Clinique La Prairie',lat:46.4562,lng:6.9003,topic:'LONGEVITY',signal:'Longevity Clinics',url:'https://cliniquelaprairie.com',region:'Europe'},
  { name:'Fountain Life',lat:26.1224,lng:-80.1373,topic:'LONGEVITY',signal:'Longevity Clinics',url:'https://fountainlife.com',region:'North America'},
  { name:'Next Health',lat:34.0522,lng:-118.2437,topic:'LONGEVITY',signal:'Longevity Clinics',url:'https://next-health.com',region:'North America'},
  { name:'Human Longevity Inc',lat:32.7157,lng:-117.1611,topic:'LONGEVITY',signal:'Longevity Clinics',url:'https://humanlongevity.com',region:'North America'},
  { name:'M42 Health',lat:24.4539,lng:54.3773,topic:'LONGEVITY',signal:'Longevity Clinics',url:'https://m42.health',region:'GCC·MENA'},
  { name:'Nordic Clinic',lat:59.3293,lng:18.0686,topic:'LONGEVITY',signal:'Longevity Clinics',url:'https://nordicclinic.se',region:'Europe'},
  { name:'Upgrade Labs',lat:34.0195,lng:-118.4912,topic:'LONGEVITY',signal:'Longevity Clinics',url:'https://upgradelabs.com',region:'North America'},
  { name:'DNA Health & Wellness Dubai',lat:25.2048,lng:55.2708,topic:'LONGEVITY',signal:'Longevity Clinics',url:'https://dnahealthwellness.com',region:'GCC·MENA'},
  { name:'Lanserhof Tegernsee',lat:47.7167,lng:11.7500,topic:'LONGEVITY',signal:'Wellness Resorts',url:'https://lanserhof.com',region:'Europe'},
  { name:'VIVAMAYR Maria Worth',lat:46.6167,lng:14.1667,topic:'LONGEVITY',signal:'Wellness Resorts',url:'https://viva-mayr.com',region:'Europe'},
  { name:'SHA Wellness Clinic',lat:38.6667,lng:-0.0833,topic:'LONGEVITY',signal:'Wellness Resorts',url:'https://shawellness.com',region:'Europe'},
  { name:'Six Senses Ibiza',lat:38.9067,lng:1.4206,topic:'LONGEVITY',signal:'Wellness Resorts',url:'https://sixsenses.com',region:'Europe'},
  { name:'Kamalaya Koh Samui',lat:9.4756,lng:100.0169,topic:'LONGEVITY',signal:'Wellness Resorts',url:'https://kamalaya.com',region:'Asia'},
  { name:'Chiva-Som',lat:12.5706,lng:99.9576,topic:'LONGEVITY',signal:'Wellness Resorts',url:'https://chivasom.com',region:'Asia'},
  { name:'THE WELL NYC',lat:40.7128,lng:-74.0060,topic:'LONGEVITY',signal:'Wellness Resorts',url:'https://thewell.life',region:'North America'},
  { name:'Aman Venice',lat:45.4341,lng:12.3280,topic:'LONGEVITY',signal:'Wellness Resorts',url:'https://aman.com',region:'Europe'},
  { name:'Como Shambhala Bali',lat:-8.5069,lng:115.2625,topic:'LONGEVITY',signal:'Wellness Resorts',url:'https://comohotels.com',region:'Asia'},
  { name:'Buck Institute for Research on Aging',lat:38.0965,lng:-122.5597,topic:'LONGEVITY',signal:'Research Institutions',url:'https://buckinstitute.org',region:'North America'},
  { name:'Hevolution Foundation',lat:24.7136,lng:46.6753,topic:'LONGEVITY',signal:'Research Institutions',url:'https://hevolution.com',region:'GCC·MENA'},
  { name:'Glenn Foundation',lat:37.4419,lng:-122.1430,topic:'LONGEVITY',signal:'Research Institutions',url:'https://glennfoundation.org',region:'North America'},
  { name:'Aspire Academy',lat:25.2631,lng:51.4373,topic:'PERFORMANCE',signal:'Performance Labs',url:'https://aspire.qa',region:'GCC·MENA'},
  { name:'EXOS',lat:33.4484,lng:-112.0740,topic:'PERFORMANCE',signal:'Performance Labs',url:'https://teamexos.com',region:'North America'},
  { name:'P3 Applied Sports Science',lat:34.4208,lng:-119.6982,topic:'PERFORMANCE',signal:'Performance Labs',url:'https://p3.md',region:'North America'},
  { name:'UFC Performance Institute',lat:36.1699,lng:-115.1398,topic:'PERFORMANCE',signal:'Performance Labs',url:'https://ufcpi.com',region:'North America'},
  { name:'Loughborough University Sport',lat:52.7718,lng:-1.2263,topic:'PERFORMANCE',signal:'Performance Labs',url:'https://lboro.ac.uk',region:'Europe'},
  { name:'Australian Institute of Sport',lat:-35.2041,lng:149.1213,topic:'PERFORMANCE',signal:'Performance Labs',url:'https://ais.gov.au',region:'ANZ'},
  { name:'INSEP Paris',lat:48.8196,lng:2.4372,topic:'PERFORMANCE',signal:'Performance Labs',url:'https://insep.fr',region:'Europe'},
  { name:'Altitude Centre London',lat:51.5074,lng:-0.1278,topic:'PERFORMANCE',signal:'Altitude & Hypoxic Training',url:'https://altitudecentre.com',region:'Europe'},
  { name:'Oxygen Ark Dubai',lat:25.2048,lng:55.2708,topic:'PERFORMANCE',signal:'Altitude & Hypoxic Training',url:'https://oxygenark.com',region:'GCC·MENA'},
  { name:'Stratosphere ATC',lat:25.1972,lng:55.2744,topic:'PERFORMANCE',signal:'Altitude & Hypoxic Training',url:'https://stratosphereatc.com',region:'GCC·MENA'},
  { name:'Hypoxico',lat:40.7128,lng:-74.0060,topic:'PERFORMANCE',signal:'Altitude & Hypoxic Training',url:'https://hypoxico.com',region:'North America'},
  { name:'Swiss Olympic Medical Center',lat:46.9480,lng:7.4474,topic:'PERFORMANCE',signal:'Altitude & Hypoxic Training',url:'https://swiss-sport.ch',region:'Europe'},
  { name:'Restore Hyper Wellness',lat:30.2672,lng:-97.7431,topic:'PERFORMANCE',signal:'Recovery & Biohacking',url:'https://restorehyperwellness.com',region:'North America'},
  { name:'Valiant Clinic Dubai',lat:25.0657,lng:55.1713,topic:'PERFORMANCE',signal:'Recovery & Biohacking',url:'https://valiantclinic.com',region:'GCC·MENA'},
  { name:'Biohax International',lat:59.6562,lng:17.8509,topic:'PERFORMANCE',signal:'Recovery & Biohacking',url:'https://biohax.tech',region:'Europe'},
  { name:'Hyperice',lat:33.6846,lng:-117.8265,topic:'PERFORMANCE',signal:'Recovery & Biohacking',url:'https://hyperice.com',region:'North America'},
  { name:'WHOOP HQ',lat:42.3601,lng:-71.0589,topic:'PERFORMANCE',signal:'Wearable Companies',url:'https://whoop.com',region:'North America'},
  { name:'Oura Ring HQ',lat:65.0121,lng:25.4651,topic:'PERFORMANCE',signal:'Wearable Companies',url:'https://ouraring.com',region:'Europe'},
  { name:'Garmin HQ',lat:38.8814,lng:-94.8191,topic:'PERFORMANCE',signal:'Wearable Companies',url:'https://garmin.com',region:'North America'},
  { name:'Polar Electro',lat:65.0121,lng:25.4651,topic:'PERFORMANCE',signal:'Wearable Companies',url:'https://polar.com',region:'Europe'},
  { name:'Dexcom',lat:32.8801,lng:-117.2340,topic:'PERFORMANCE',signal:'Wearable Companies',url:'https://dexcom.com',region:'North America'},
  { name:'Hospital for Special Surgery',lat:40.7654,lng:-73.9547,topic:'PERFORMANCE',signal:'Sports Medicine Clinics',url:'https://hss.edu',region:'North America'},
  { name:'Aspetar Orthopaedic Hospital',lat:25.2677,lng:51.5134,topic:'PERFORMANCE',signal:'Sports Medicine Clinics',url:'https://aspetar.com',region:'GCC·MENA'},
  { name:'a16z Bio Fund',lat:37.4419,lng:-122.1430,topic:'INVESTMENTS',signal:'VC Funds',url:'https://a16z.com/bio',region:'North America'},
  { name:'General Catalyst',lat:42.3736,lng:-71.1097,topic:'INVESTMENTS',signal:'VC Funds',url:'https://generalcatalyst.com',region:'North America'},
  { name:'Flagship Pioneering',lat:42.3736,lng:-71.1097,topic:'INVESTMENTS',signal:'VC Funds',url:'https://flagshippioneer.com',region:'North America'},
  { name:'GV Google Ventures',lat:37.4419,lng:-122.1430,topic:'INVESTMENTS',signal:'VC Funds',url:'https://gv.com',region:'North America'},
  { name:'Khosla Ventures',lat:37.4419,lng:-122.1530,topic:'INVESTMENTS',signal:'VC Funds',url:'https://khoslaventures.com',region:'North America'},
  { name:'Apollo Health Ventures',lat:52.5200,lng:13.4050,topic:'INVESTMENTS',signal:'VC Funds',url:'https://apollo.health',region:'Europe'},
  { name:'Longevity Vision Fund',lat:51.5074,lng:-0.1278,topic:'INVESTMENTS',signal:'VC Funds',url:'https://longevity.vc',region:'Europe'},
  { name:'Sofinnova Partners',lat:48.8566,lng:2.3522,topic:'INVESTMENTS',signal:'VC Funds',url:'https://sofinnova.com',region:'Europe'},
  { name:'Forbion',lat:52.3702,lng:4.8952,topic:'INVESTMENTS',signal:'VC Funds',url:'https://forbion.com',region:'Europe'},
  { name:'Novo Holdings',lat:55.6761,lng:12.5683,topic:'INVESTMENTS',signal:'VC Funds',url:'https://novoholdings.dk',region:'Europe'},
  { name:'OrbiMed',lat:40.7128,lng:-74.0060,topic:'INVESTMENTS',signal:'VC Funds',url:'https://orbimed.com',region:'North America'},
  { name:'Bessemer Venture Partners',lat:37.7749,lng:-122.4194,topic:'INVESTMENTS',signal:'VC Funds',url:'https://bvp.com',region:'North America'},
  { name:'F-Prime Capital',lat:42.3601,lng:-71.0589,topic:'INVESTMENTS',signal:'VC Funds',url:'https://fprimecapital.com',region:'North America'},
  { name:'Mubadala Health',lat:24.4539,lng:54.3773,topic:'INVESTMENTS',signal:'Sovereign & State Funds',url:'https://mubadala.com',region:'GCC·MENA'},
  { name:'ADQ',lat:24.4539,lng:54.3873,topic:'INVESTMENTS',signal:'Sovereign & State Funds',url:'https://adq.ae',region:'GCC·MENA'},
  { name:'PIF Health',lat:24.7136,lng:46.6753,topic:'INVESTMENTS',signal:'Sovereign & State Funds',url:'https://pif.gov.sa',region:'GCC·MENA'},
  { name:'QIA',lat:25.2854,lng:51.5310,topic:'INVESTMENTS',signal:'Sovereign & State Funds',url:'https://qia.qa',region:'GCC·MENA'},
  { name:'Temasek',lat:1.3521,lng:103.8198,topic:'INVESTMENTS',signal:'Sovereign & State Funds',url:'https://temasek.com.sg',region:'Asia'},
  { name:'GIC Singapore',lat:1.3521,lng:103.8298,topic:'INVESTMENTS',signal:'Sovereign & State Funds',url:'https://gic.com.sg',region:'Asia'},
  { name:'Kuwait Investment Authority',lat:29.3759,lng:47.9774,topic:'INVESTMENTS',signal:'Sovereign & State Funds',url:'https://kia.gov.kw',region:'GCC·MENA'},
  { name:'Wellcome Trust',lat:51.5267,lng:-0.1340,topic:'INVESTMENTS',signal:'Family Offices',url:'https://wellcome.org',region:'Europe'},
  { name:'Bezos Day One Fund',lat:47.6062,lng:-122.3321,topic:'INVESTMENTS',signal:'Family Offices',url:'https://dayonefund.org',region:'North America'},
  { name:'Li Ka-shing Foundation',lat:22.3193,lng:114.1694,topic:'INVESTMENTS',signal:'Family Offices',url:'https://lksf.org',region:'Asia'},
  { name:'Aga Khan Health Services',lat:46.2044,lng:6.1432,topic:'INVESTMENTS',signal:'Family Offices',url:'https://akdn.org',region:'Europe'},
  { name:'Milken Institute',lat:34.0522,lng:-118.2537,topic:'INVESTMENTS',signal:'Family Offices',url:'https://milkeninstitute.org',region:'North America'},
  { name:'Stavros Niarchos Foundation',lat:37.9838,lng:23.7275,topic:'INVESTMENTS',signal:'Family Offices',url:'https://snf.org',region:'Europe'},
  { name:'Dolby Family Ventures',lat:37.7749,lng:-122.4294,topic:'INVESTMENTS',signal:'Family Offices',url:'https://dolby.com',region:'North America'},
  { name:'McLean Hospital',lat:42.3236,lng:-71.1745,topic:'MENTAL HEALTH',signal:'Research Centers',url:'https://mcleanhospital.org',region:'North America'},
  { name:'NIMH',lat:39.0024,lng:-77.1056,topic:'MENTAL HEALTH',signal:'Research Centers',url:'https://nimh.nih.gov',region:'North America'},
  { name:'Stanley Center Broad Institute',lat:42.3628,lng:-71.0912,topic:'MENTAL HEALTH',signal:'Research Centers',url:'https://broadinstitute.org/stanley',region:'North America'},
  { name:'CAMH Toronto',lat:43.6426,lng:-79.4189,topic:'MENTAL HEALTH',signal:'Research Centers',url:'https://camh.ca',region:'North America'},
  { name:'Maudsley Hospital',lat:51.4545,lng:-0.0806,topic:'MENTAL HEALTH',signal:'Research Centers',url:'https://slam.nhs.uk',region:'Europe'},
  { name:'Max Planck Institute of Psychiatry',lat:48.1351,lng:11.5820,topic:'MENTAL HEALTH',signal:'Research Centers',url:'https://psych.mpg.de',region:'Europe'},
  { name:'Black Dog Institute',lat:-33.8688,lng:151.2093,topic:'MENTAL HEALTH',signal:'Research Centers',url:'https://blackdoginstitute.org.au',region:'ANZ'},
  { name:'Karolinska Institute Psychiatry',lat:59.3293,lng:18.0686,topic:'MENTAL HEALTH',signal:'Research Centers',url:'https://ki.se',region:'Europe'},
  { name:'Institute of Mental Health Singapore',lat:1.3839,lng:103.8467,topic:'MENTAL HEALTH',signal:'Research Centers',url:'https://imh.com.sg',region:'Asia'},
  { name:'Johns Hopkins Psychiatry',lat:39.2976,lng:-76.5926,topic:'MENTAL HEALTH',signal:'Research Centers',url:'https://hopkinsmedicine.org/psychiatry',region:'North America'},
  { name:'MAPS',lat:37.3382,lng:-121.8863,topic:'MENTAL HEALTH',signal:'Psychedelic & Ketamine Clinics',url:'https://maps.org',region:'North America'},
  { name:'Awakn Life Sciences',lat:51.4545,lng:-2.5879,topic:'MENTAL HEALTH',signal:'Psychedelic & Ketamine Clinics',url:'https://awakn.life',region:'Europe'},
  { name:'Synthesis Institute',lat:52.3702,lng:4.8952,topic:'MENTAL HEALTH',signal:'Psychedelic & Ketamine Clinics',url:'https://synthesisretreat.com',region:'Europe'},
  { name:'Beckley Foundation',lat:51.7520,lng:-1.2577,topic:'MENTAL HEALTH',signal:'Psychedelic & Ketamine Clinics',url:'https://beckleyfoundation.org',region:'Europe'},
  { name:'Numinus',lat:49.2827,lng:-123.1207,topic:'MENTAL HEALTH',signal:'Psychedelic & Ketamine Clinics',url:'https://numinus.com',region:'North America'},
  { name:'Field Trip Health NYC',lat:40.7580,lng:-73.9855,topic:'MENTAL HEALTH',signal:'Psychedelic & Ketamine Clinics',url:'https://fieldtriphealth.com',region:'North America'},
  { name:'Compass Pathways',lat:51.5074,lng:-0.1378,topic:'MENTAL HEALTH',signal:'Psychedelic & Ketamine Clinics',url:'https://compasspathways.com',region:'Europe'},
  { name:'WHO Mental Health',lat:46.2338,lng:6.1169,topic:'MENTAL HEALTH',signal:'WHO & Policy Bodies',url:'https://who.int/mental-health',region:'Europe'},
  { name:'PAHO',lat:38.9072,lng:-77.0369,topic:'MENTAL HEALTH',signal:'WHO & Policy Bodies',url:'https://paho.org',region:'North America'},
  { name:'European Mental Health Alliance',lat:50.8503,lng:4.3517,topic:'MENTAL HEALTH',signal:'WHO & Policy Bodies',url:'https://mentalhealth-europe.org',region:'Europe'},
  { name:'NIH Clinical Center',lat:39.0024,lng:-77.1156,topic:'DISCOVERIES',signal:'Clinical Trial Sites',url:'https://clinicalcenter.nih.gov',region:'North America'},
  { name:'Wellcome Trust',lat:51.5267,lng:-0.1240,topic:'DISCOVERIES',signal:'Clinical Trial Sites',url:'https://wellcome.org',region:'Europe'},
  { name:'Weizmann Institute',lat:31.9050,lng:34.8090,topic:'DISCOVERIES',signal:'Clinical Trial Sites',url:'https://weizmann.ac.il',region:'GCC·MENA'},
  { name:'RIKEN',lat:35.6762,lng:139.6503,topic:'DISCOVERIES',signal:'Clinical Trial Sites',url:'https://riken.jp',region:'Asia'},
  { name:'Garvan Institute',lat:-33.8688,lng:151.2193,topic:'DISCOVERIES',signal:'Clinical Trial Sites',url:'https://garvan.org.au',region:'ANZ'},
  { name:'A*STAR Singapore',lat:1.3521,lng:103.8098,topic:'DISCOVERIES',signal:'Clinical Trial Sites',url:'https://a-star.edu.sg',region:'Asia'},
  { name:'Harvard Medical School',lat:42.3354,lng:-71.1048,topic:'DISCOVERIES',signal:'Research Universities',url:'https://hms.harvard.edu',region:'North America'},
  { name:'Johns Hopkins Medicine',lat:39.2976,lng:-76.5826,topic:'DISCOVERIES',signal:'Research Universities',url:'https://hopkinsmedicine.org',region:'North America'},
  { name:'Oxford Medical Sciences',lat:51.7520,lng:-1.2577,topic:'DISCOVERIES',signal:'Research Universities',url:'https://medsci.ox.ac.uk',region:'Europe'},
  { name:'Cambridge Medical',lat:52.2053,lng:0.1218,topic:'DISCOVERIES',signal:'Research Universities',url:'https://cam.ac.uk',region:'Europe'},
  { name:'Stanford Medicine',lat:37.4330,lng:-122.1750,topic:'DISCOVERIES',signal:'Research Universities',url:'https://med.stanford.edu',region:'North America'},
  { name:'ETH Zurich',lat:47.3769,lng:8.5417,topic:'DISCOVERIES',signal:'Research Universities',url:'https://ethz.ch',region:'Europe'},
  { name:'UCL Medicine',lat:51.5246,lng:-0.1340,topic:'DISCOVERIES',signal:'Research Universities',url:'https://ucl.ac.uk',region:'Europe'},
  { name:'NUS Medicine',lat:1.2966,lng:103.7764,topic:'DISCOVERIES',signal:'Research Universities',url:'https://medicine.nus.edu.sg',region:'Asia'},
  { name:'Karolinska Institute',lat:59.3293,lng:18.0786,topic:'DISCOVERIES',signal:'Research Universities',url:'https://ki.se',region:'Europe'},
  { name:'Kendall Square Cambridge',lat:42.3628,lng:-71.0912,topic:'DISCOVERIES',signal:'Biotech Hubs',url:'https://cambridgema.gov',region:'North America'},
  { name:'Mission Bay Biotech Hub',lat:37.7665,lng:-122.3919,topic:'DISCOVERIES',signal:'Biotech Hubs',url:'https://missionbaysf.com',region:'North America'},
  { name:'Biopolis Singapore',lat:1.3000,lng:103.7870,topic:'DISCOVERIES',signal:'Biotech Hubs',url:'https://a-star.edu.sg/biopolis',region:'Asia'},
  { name:'HealthHub Dubai',lat:25.2048,lng:55.2808,topic:'DISCOVERIES',signal:'Biotech Hubs',url:'https://dubaihealth.ae',region:'GCC·MENA'},
  { name:'Broad Institute',lat:42.3628,lng:-71.1012,topic:'DISCOVERIES',signal:'Biotech Hubs',url:'https://broadinstitute.org',region:'North America'},
  { name:'BioCity Nottingham',lat:52.9548,lng:-1.1581,topic:'DISCOVERIES',signal:'Biotech Hubs',url:'https://biocity.co.uk',region:'Europe'},
  { name:'CDC',lat:33.7990,lng:-84.3251,topic:'THREATS',signal:'Health Agencies',url:'https://cdc.gov',region:'North America'},
  { name:'WHO HQ',lat:46.2338,lng:6.1169,topic:'THREATS',signal:'Health Agencies',url:'https://who.int',region:'Europe'},
  { name:'ECDC',lat:59.3327,lng:18.0656,topic:'THREATS',signal:'Health Agencies',url:'https://ecdc.europa.eu',region:'Europe'},
  { name:'NIH',lat:39.0024,lng:-77.1056,topic:'THREATS',signal:'Health Agencies',url:'https://nih.gov',region:'North America'},
  { name:'Robert Koch Institute',lat:52.5397,lng:13.3505,topic:'THREATS',signal:'Health Agencies',url:'https://rki.de',region:'Europe'},
  { name:'Africa CDC',lat:9.0054,lng:38.7636,topic:'THREATS',signal:'Health Agencies',url:'https://africacdc.org',region:'Africa'},
  { name:'PHAC Canada',lat:45.4215,lng:-75.6972,topic:'THREATS',signal:'Health Agencies',url:'https://phac-aspc.gc.ca',region:'North America'},
  { name:'ICMR India',lat:28.6139,lng:77.2090,topic:'THREATS',signal:'Health Agencies',url:'https://icmr.gov.in',region:'Asia'},
  { name:'Chinese CDC',lat:39.9042,lng:116.4074,topic:'THREATS',signal:'Health Agencies',url:'https://chinacdc.cn',region:'Asia'},
  { name:'Institut Pasteur',lat:48.8422,lng:2.3117,topic:'THREATS',signal:'Health Agencies',url:'https://pasteur.fr',region:'Europe'},
  { name:'PAHO Washington',lat:38.9072,lng:-77.0469,topic:'THREATS',signal:'Health Agencies',url:'https://paho.org',region:'North America'},
  { name:'Johns Hopkins Center for Health Security',lat:39.2976,lng:-76.6026,topic:'THREATS',signal:'Biosecurity Centers',url:'https://centerforhealthsecurity.org',region:'North America'},
  { name:'Wellcome Sanger Institute',lat:52.0796,lng:0.1833,topic:'THREATS',signal:'Biosecurity Centers',url:'https://sanger.ac.uk',region:'Europe'},
  { name:'NTI Global Health Security',lat:38.9072,lng:-77.0369,topic:'THREATS',signal:'Biosecurity Centers',url:'https://nti.org',region:'North America'},
  { name:'Chatham House Global Health',lat:51.5074,lng:-0.1378,topic:'THREATS',signal:'Biosecurity Centers',url:'https://chathamhouse.org',region:'Europe'},
  { name:'USAMRIID',lat:39.4395,lng:-77.4497,topic:'THREATS',signal:'Biosecurity Centers',url:'https://usamriid.army.mil',region:'North America'},
  { name:'ProMED Mail',lat:42.3601,lng:-71.0589,topic:'THREATS',signal:'Biosecurity Centers',url:'https://promedmail.org',region:'North America'},
  { name:'FDA HQ',lat:39.0024,lng:-77.1156,topic:'THREATS',signal:'Product Recalls',url:'https://fda.gov/safety/recalls',region:'North America'},
  { name:'EFSA',lat:43.7231,lng:10.4018,topic:'THREATS',signal:'Product Recalls',url:'https://efsa.europa.eu',region:'Europe'},
  { name:'EMA',lat:52.3702,lng:4.8852,topic:'THREATS',signal:'Product Recalls',url:'https://ema.europa.eu',region:'Europe'},
  { name:'Health Canada',lat:45.4215,lng:-75.7072,topic:'THREATS',signal:'Product Recalls',url:'https://canada.ca/health',region:'North America'},
  { name:'TGA Australia',lat:-35.2809,lng:149.1300,topic:'THREATS',signal:'Product Recalls',url:'https://tga.gov.au',region:'ANZ'},
  { name:'MHRA UK',lat:51.5074,lng:-0.1178,topic:'THREATS',signal:'Product Recalls',url:'https://mhra.gov.uk',region:'Europe'},
];
export async function GET() { return NextResponse.json(LOCATIONS); }

