import { NextResponse } from 'next/server';
const LOCATIONS = [
  { name: "Altos Labs", lat: 37.4419, lng: -122.1430, topic: "LONGEVITY", type: "Biotech", url: "https://www.altoslabs.com", region: "North America" },
  { name: "Calico", lat: 37.3861, lng: -122.0839, topic: "LONGEVITY", type: "Biotech", url: "https://www.calicolabs.com", region: "North America" },
  { name: "Fountain Life", lat: 26.1224, lng: -80.1373, topic: "LONGEVITY", type: "Clinic", url: "https://fountainlife.com", region: "North America" },
  { name: "Clinique La Prairie", lat: 46.4312, lng: 6.9107, topic: "LONGEVITY", type: "Wellness Resort", url: "https://cliniquelaprairie.com", region: "Europe" },
  { name: "Lanserhof", lat: 47.5162, lng: 12.0423, topic: "LONGEVITY", type: "Wellness Resort", url: "https://lanserhof.com", region: "Europe" },
  { name: "VIVAMAYR", lat: 46.6167, lng: 14.2667, topic: "LONGEVITY", type: "Wellness Resort", url: "https://vivamayr.com", region: "Europe" },
  { name: "SHA Wellness Clinic", lat: 38.6393, lng: -0.0731, topic: "LONGEVITY", type: "Wellness Resort", url: "https://shawellness.com", region: "Europe" },
  { name: "M42", lat: 24.4539, lng: 54.3773, topic: "LONGEVITY", type: "Biotech", url: "https://m42.ae", region: "GCC·MENA" },
  { name: "DNA Health & Wellness", lat: 25.2048, lng: 55.2708, topic: "LONGEVITY", type: "Clinic", url: "https://dnahealthwellness.com", region: "GCC·MENA" },
  { name: "Six Senses", lat: 27.1751, lng: 78.0421, topic: "LONGEVITY", type: "Wellness Resort", url: "https://sixsenses.com", region: "Asia" },
  { name: "Kamalaya", lat: 9.5120, lng: 100.0136, topic: "LONGEVITY", type: "Wellness Resort", url: "https://kamalaya.com", region: "Asia" },
  { name: "Chiva-Som", lat: 12.5684, lng: 99.9577, topic: "LONGEVITY", type: "Wellness Resort", url: "https://chivasom.com", region: "Asia" },
  { name: "Next Health", lat: 34.0522, lng: -118.2437, topic: "LONGEVITY", type: "Clinic", url: "https://next-health.com", region: "North America" },
  { name: "Upgrade Labs", lat: 34.0195, lng: -118.4912, topic: "LONGEVITY", type: "Clinic", url: "https://upgradelabs.com", region: "North America" },
  { name: "THE WELL", lat: 40.7128, lng: -74.0060, topic: "LONGEVITY", type: "Wellness Club", url: "https://thewell.world", region: "North America" },
  { name: "Nordic Clinic Stockholm", lat: 59.3293, lng: 18.0686, topic: "LONGEVITY", type: "Clinic", url: "https://nordicclinic.com", region: "Europe" },
  { name: "Insilico Medicine", lat: 22.3193, lng: 114.1694, topic: "LONGEVITY", type: "Biotech", url: "https://insilico.com", region: "Asia" },
  { name: "Aspire Academy", lat: 25.2644, lng: 51.4410, topic: "PERFORMANCE", type: "Performance Lab", url: "https://aspire.qa", region: "GCC·MENA" },
  { name: "EXOS", lat: 33.4484, lng: -112.0740, topic: "PERFORMANCE", type: "Performance Lab", url: "https://teamexos.com", region: "North America" },
  { name: "P3 Applied Sports Science", lat: 34.4208, lng: -119.6982, topic: "PERFORMANCE", type: "Performance Lab", url: "https://p3.md", region: "North America" },
  { name: "UFC Performance Institute", lat: 36.1699, lng: -115.1398, topic: "PERFORMANCE", type: "Performance Lab", url: "https://ufc.com/performance-institute", region: "North America" },
  { name: "Loughborough University", lat: 52.7721, lng: -1.2062, topic: "PERFORMANCE", type: "Performance Lab", url: "https://lboro.ac.uk", region: "Europe" },
  { name: "WHOOP HQ", lat: 42.3601, lng: -71.0589, topic: "PERFORMANCE", type: "Wearable", url: "https://whoop.com", region: "North America" },
  { name: "Oura HQ", lat: 65.0121, lng: 25.4651, topic: "PERFORMANCE", type: "Wearable", url: "https://ouraring.com", region: "Europe" },
  { name: "Garmin HQ", lat: 38.8614, lng: -94.7977, topic: "PERFORMANCE", type: "Wearable", url: "https://garmin.com", region: "North America" },
  { name: "Altitude Centre London", lat: 51.5074, lng: -0.1200, topic: "PERFORMANCE", type: "Altitude Training", url: "https://altitudecentre.com", region: "Europe" },
  { name: "Restore Hyper Wellness", lat: 30.2672, lng: -97.7431, topic: "PERFORMANCE", type: "Recovery", url: "https://restorehyperwellness.com", region: "North America" },
  { name: "Valiant Clinic", lat: 25.2048, lng: 55.2708, topic: "PERFORMANCE", type: "Sports Clinic", url: "https://valiantclinics.com", region: "GCC·MENA" },
  { name: "Oxygen Ark", lat: 25.1800, lng: 55.2600, topic: "PERFORMANCE", type: "HBOT Clinic", url: "https://oxygenark.com", region: "GCC·MENA" },
  { name: "Andreessen Horowitz (a16z)", lat: 37.3861, lng: -122.0839, topic: "INVESTMENTS", type: "VC Fund", url: "https://a16z.com/bio-health/", region: "North America" },
  { name: "General Catalyst", lat: 42.3736, lng: -71.1106, topic: "INVESTMENTS", type: "VC Fund", url: "https://generalcatalyst.com", region: "North America" },
  { name: "Flagship Pioneering", lat: 42.3601, lng: -71.0500, topic: "INVESTMENTS", type: "VC Fund", url: "https://flagshippioneeering.com", region: "North America" },
  { name: "Mubadala Health", lat: 24.4539, lng: 54.3773, topic: "INVESTMENTS", type: "Sovereign Fund", url: "https://mubadala.com", region: "GCC·MENA" },
  { name: "Apollo Health Ventures", lat: 52.5200, lng: 13.4050, topic: "INVESTMENTS", type: "VC Fund", url: "https://apollo.health", region: "Europe" },
  { name: "Longevity Vision Fund", lat: 51.5074, lng: -0.1000, topic: "INVESTMENTS", type: "VC Fund", url: "https://longevity.vc", region: "Europe" },
];
export async function GET() { return NextResponse.json(LOCATIONS); }
